import * as THREE from 'three';
import { DEFAULT_SIZE, DEFAULT_SEGMENTS, sampleHeight } from './environment/elements.js';
import { buildEnvironment, getEnvironment, DEFAULT_ENVIRONMENT_ID } from './environment/presets.js';

/**
 * The ground, as the mesh side of an assembled environment. Everything about
 * the world's shape and colour is generated by `js/environment/`, which knows
 * nothing about Three.js; this class turns the field it hands back into
 * geometry and answers the height queries the flight model asks.
 */
export class Terrain {
    constructor(scene, environmentId = DEFAULT_ENVIRONMENT_ID, world = {}) {
        this.scene    = scene;
        this.size     = DEFAULT_SIZE;
        this.segments = DEFAULT_SEGMENTS;
        this.mesh     = null;
        this.built    = null;

        this.setEnvironment(environmentId, world);
    }

    /**
     * Flies a different world. The old mesh and its geometry are released
     * rather than left in the scene, so switching environments from the
     * settings panel does not stack them up behind each other.
     *
     * A world is more than the preset it is drawn from: the same description
     * seeded differently, or with a strip in it rather than without one, is a
     * different world and is rebuilt as one. What is not rebuilt is asking for
     * the world already on screen, which is what keeps the panel from
     * regenerating the ground every time a setting near it is touched.
     *
     * Returns true when the world actually changed.
     */
    setEnvironment(environmentId, world = {}) {
        const environment = getEnvironment(environmentId);
        const asked = {
            id: environment.id,
            seed: world.seed ?? environment.seed,
            runway: world.runway ?? false,
            base: world.base ?? null
        };

        if (this.mesh && sameWorld(this.built, asked)) return false;

        this.built       = asked;
        this.environment = environment;
        this.maxHeight   = asked.base?.maxHeight ?? environment.base?.maxHeight ?? 480;
        this.field       = buildEnvironment(environment, {
            size: this.size,
            segments: this.segments,
            seed: asked.seed,
            base: asked.base,
            runway: asked.runway
        });

        this.build();
        return true;
    }

    /** The strips cut into the world being flown, for anything landing on one. */
    getRunways() {
        return this.field.runways;
    }

    /** The one strip a world carries, or null for a world generated without one. */
    getRunway() {
        return this.field.runways[0] ?? null;
    }

    build() {
        if (this.mesh) {
            this.scene.remove(this.mesh);
            this.mesh.geometry.dispose();
            this.mesh.material.dispose();
        }

        const geo = new THREE.PlaneGeometry(this.size, this.size, this.segments, this.segments);
        geo.rotateX(-Math.PI / 2);

        // The field is sampled in the same row-by-row order the plane lays its
        // vertices out in, so the heights and colours drop straight in.
        const pos = geo.attributes.position;
        for (let i = 0; i < pos.count; i++) {
            pos.setY(i, this.field.height[i]);
        }

        geo.setAttribute('color', new THREE.Float32BufferAttribute(this.field.color.slice(), 3));
        geo.computeVertexNormals();

        this.mesh = new THREE.Mesh(
            geo,
            new THREE.MeshLambertMaterial({ vertexColors: true })
        );
        this.scene.add(this.mesh);
    }

    getTerrainHeightAt(x, z) {
        return sampleHeight(this.field, x, z);
    }

    /** The square the world covers, for anything that has to stay inside it. */
    getBounds() {
        const half = this.size / 2;
        return { minX: -half, maxX: half, minZ: -half, maxZ: half };
    }
}

/** Whether two asks would generate the same ground, down to the strip on it. */
function sameWorld(built, asked) {
    return built != null
        && built.id === asked.id
        && built.seed === asked.seed
        && JSON.stringify(built.runway) === JSON.stringify(asked.runway)
        && JSON.stringify(built.base) === JSON.stringify(asked.base);
}
